config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  resources :nodes
  resources :accounts
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_many :children, class_name: "Node", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Node"#, foreign_key: "manager_id"

  def self.create_node(path, folder=nil)
    if File.exist?(path) then
      nd = self.new
      
      #nd.name = File.basename(path)
      nd.name = path
      nd.mtime = File.mtime(path)
      nd.parent = folder

      if File.directory?(path) then
        nd.is_folder = true
      else
        nd.is_folder = false
        nd.size = File.size(path)
      end

      nd.save
      return nd
    else
      puts "cannot create node [#{path}]"
      return nil
    end
  end
  
  def create_descendants
    return if not self.is_folder
    
    yield 'stage 1', 0 if block_given?
    self.create_children
    yield 'stage 2', 0 if block_given?
    self.cal_size
    yield 'stage 3', 0 if block_given?
    self.cal_md5
  end
  
  def create_children
    return if not self.is_folder
    
    ns = Dir.glob(self.name+'/*')
    ns.delete('.')
    ns.delete('..')
    ns.sort!
    
    ns.each do |child|
      nd = Node.create_node(child, self)
      #puts nd.name
      if nd.is_folder then
        nd.create_children
      end
    end
  end
  
  def cal_size
    sz = 0
    self.children.each do |child|
      child.cal_size if child.size == nil
      sz = sz + child.size
    end
    
    self.size = sz
    self.save
  end

  def cal_md5
    if self.is_folder then
      md5 = Digest::MD5.new
      self.children.each do |child|
        child.cal_md5 if child.md5 == nil
        md5 << child.md5
      end
      #self.md5 = md5.digest.force_encoding('utf-8')
      self.md5 = md5.hexdigest
      self.save
    else
      self.md5 = Digest::MD5.file(self.name).hexdigest
      self.save
    end
  end

  def md5_str
    return 'unknown' if self.md5 == nil
    return self.md5
    #if use save digest intead of hexdigest, use this to convert the binary to string
    #return self.md5.unpack('H*')[0]
  end

  def self.top(n=25)
    sql = "select md5, size*(count(*)-1) size from nodes group by md5 having count(*)>1 order by size desc limit #{n};"
    result = self.connection.execute(sql)
    mds = []
    result.each do |r|
      mds << {:md5=>r[0], :size=>r[1]}
    end
    return mds
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params[:account].permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @mds = Node.top
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    if params[:digest] != nil then
      @nodes = Node.where("md5 = ?", params[:digest]).paginate(:page => params[:page], :per_page => 25)
    else
      @nodes = Node.paginate(:page => params[:page], :per_page => 25)
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @nodes = @node.children.paginate(:page => params[:page], :per_page => 25)
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.create_node(node_params[:name])

    respond_to do |format|
      if @node.save
        #@node.delay.create_descendants
        Delayed::Job.enqueue ProgressJob.new(@node, 'create_descendants')
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params[:node]
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
  def node_type(node)
    return node.is_folder ? 'Y' : 'N'
  end
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :name %>
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to account.name, account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/home/top.html.erb
<h1>Home</h1>
<table>
<tr><th>md5</th><th>size</th></tr>
<%@mds.each do |md|%> 
<tr><td><%= link_to md[:md5], nodes_path(:digest=>md[:md5]) %>
<%=%></td><td><%=md[:size]%></td></tr>
<%end%>
<table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :name%>
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<%= will_paginate @nodes %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= link_to node.name, node %></td>
        <td><%= link_to node_type(node), node %></td>
        <td><%= link_to node.size, node %></td>
        <td><%= link_to node.mtime, node %></td>
        <td><%= link_to node.md5_str, node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @nodes %>
<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <tr><td>name</td><td><%=@node.name%></td></tr>
  <tr><td>size</td><td><%=@node.size%></td></tr>
  <tr><td>md5</td><td><%=@node.md5%></td></tr>
</table>

<%= will_paginate @nodes %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= link_to node.name, node %></td>
        <td><%= link_to node_type(node), node %></td>
        <td><%= link_to node.size, node %></td>
        <td><%= link_to node.mtime, node %></td>
        <td><%= link_to node.md5_str, node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @nodes %>
<br>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>